### ISSUE TITLE
Segfault when using `--kinds-GO=f`

### ISSUE THREAD

**Issue by aleb** [universal-ctags/ctags#2430]
I'm using `/usr/local/Cellar/universal-ctags/HEAD-fd99ef5/bin/ctags`. It works fine if I run:

```
$ ctags --languages=GO  --recurse      
```

But segfaults if I run:

```
$ ctags --languages=GO --kinds-GO=f --recurse
```

Backtrace:

```
$ gdb ctags
GNU gdb (GDB) 8.3.1

Reading symbols from ctags...
(No debugging symbols found in ctags)
(gdb) run --languages=GO --kinds-GO=f --recurse
Starting program: /usr/local/bin/ctags --languages=GO --kinds-GO=f --recurse
[New Thread 0x2703 of process 71721]
[New Thread 0x1a03 of process 71721]
warning: unhandled dyld version (16)

Thread 2 received signal SIGSEGV, Segmentation fault.
0x0000000100041c6e in attachTypeRefField ()
(gdb) bt
#0  0x0000000100041c6e in attachTypeRefField ()
#1  0x0000000100040b8f in parseConstTypeVar ()
#2  0x0000000100040396 in findGoTags ()
#3  0x0000000100016002 in createTagsWithFallback1 ()
#4  0x00000001000164b0 in parseMio ()
#5  0x00000001000163fd in parseFileWithMio ()
#6  0x000000010000c6c2 in createTagsForEntry ()
#7  0x000000010000c5b3 in recurseIntoDirectory ()
#8  0x000000010000c696 in createTagsForEntry ()
#9  0x000000010000c5b3 in recurseIntoDirectory ()
#10 0x000000010000c337 in batchMakeTags ()
#11 0x000000010000c0c4 in ctags_cli_main ()
#12 0x00007fff63dd62e5 in ?? ()
#13 0x0000000000000000 in ?? ()
```

I tried rebuilding with `brew reinstall --debug universal-ctags` to have debugging symbols, but no luck.

It can be reproduced with:

```
$ mkdir /tmp/y

$ cd /tmp/y

$ cat >datasets.go <<EOF
package main

type Interval struct {
        Start, Stop string
}

EOF

$ ctags --verbose --languages=GO --kinds-GO=f datasets.go                               
[...]
OPENING datasets.go as Go language file [new]
zsh: segmentation fault  ctags --verbose --languages=GO --kinds-GO=f datasets.go
```

**Comment by aleb** [comment]
FWIW, it works fine if I replace "Start, Stop string" with "Start string".

**Comment by masatake** [comment]
Thank you for the small input:-)  It makes debugging much easier.
See #2431.

**Comment by aleb** [comment]
Thanks for the super-fast fix!
