### ISSUE TITLE
crash with ctags -R .

### ISSUE THREAD

**Issue by mcepl** [universal-ctags/ctags#2923]
The name of the parser:

The command line you used to run ctags:

```
$ ctags -R .
```

The content of input file:

source tree of the current ``master`` branch of ``openssl``.

Result is crash:
```
openssl@stitny (master)$ gdb universal-ctags -- -R .
Excess command line arguments ignored. (.)
GNU gdb (GDB; openSUSE Tumbleweed) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from universal-ctags...
Downloading separate debug info for /home/matej/archiv/knihovna/repos/openssl/universal-ctags...
Reading symbols from /home/matej/.cache/debuginfod_client/8b50f57432a46ef93eb45bc3744a399aa445446b/debuginfo...
/home/matej/archiv/knihovna/repos/openssl/-R: Adresář nebo soubor neexistuje.
(gdb) run -R .
Starting program: /usr/bin/universal-ctags -R .

Program received signal SIGSEGV, Segmentation fault.
getLanguageNameFull (language=-1431655766, noPretending=false) at main/parse.c:253
Downloading source file /usr/src/debug/universal-ctags-0+git~c77db554-1.6.x86_64/main/parse.c...
253	static const char *getLanguageNameFull (const langType language, bool noPretending)
(gdb)
(gdb) t a a bt

Thread 1 (process 22213 "universal-ctags"):
#0  getLanguageNameFull (language=-1431655766, noPretending=false) at main/parse.c:253
#1  0x0000555555600777 in getLanguageName (language=<optimized out>) at main/parse.c:281
#2  guestRequestSubmit (r=0x55555566dcb0) at main/lregex.c:2683
#3  0x0000555555601382 in matchMultitableRegexTable (offset=<optimized out>, start=<optimized out>, table=<optimized out>, lcb=<optimized out>) at main/lregex.c:2411
#4  matchMultitableRegex (lcb=0x55555566dab0, allLines=0x5555556d6110) at main/lregex.c:2602
#5  0x00005555555891b8 in matchMultitableRegex (allLines=0x5555556d6110, lcb=<optimized out>) at main/read.c:908
#6  matchLanguageMultilineRegexCommon (allLines=0x5555556d6110, func=<optimized out>, language=<optimized out>) at main/parse.c:3698
#7  matchLanguageMultitableRegex (allLines=0x5555556d6110, language=<optimized out>) at main/parse.c:3717
#8  iFileGetLine () at main/read.c:903
#9  0x00005555555f83dd in readLineFromInputFile () at main/read.c:995
#10 fileReadLineDriver () at main/lregex.c:1838
#11 findRegexTagsMainloop (driver=<optimized out>) at main/lregex.c:1832
#12 findRegexTags () at main/lregex.c:1843
#13 0x0000555555589ae4 in createTagsForFile (passCount=<optimized out>, language=52) at main/parse.c:3240
#14 createTagsWithFallback1 (language=52, exclusive_subparser=0x7fffffffdabc) at main/parse.c:3368
#15 0x0000555555574a60 in createTagsWithFallback (mio=<optimized out>, language=52, fileName=0x5555556ac260 ".github/ISSUE_TEMPLATE/bug_report.md") at main/parse.c:3454
#16 parseMio (useSourceFileTagPath=true, clientData=0x0, mio=<optimized out>, language=52, fileName=0x5555556ac260 ".github/ISSUE_TEMPLATE/bug_report.md") at main/parse.c:3613
#17 parseFileWithMio (mio=0x0, clientData=0x0, fileName=0x5555556ac260 ".github/ISSUE_TEMPLATE/bug_report.md") at main/parse.c:3659
#18 parseFile (fileName=0x5555556ac260 ".github/ISSUE_TEMPLATE/bug_report.md") at main/parse.c:3597
#19 createTagsForEntry (entryName=entryName@entry=0x5555556ac260 ".github/ISSUE_TEMPLATE/bug_report.md") at main/main.c:217
#20 0x0000555555575ca6 in recurseUsingOpendir (dirName=0x5555556a41f0 ".github/ISSUE_TEMPLATE") at main/main.c:112
#21 recurseIntoDirectory (dirName=dirName@entry=0x5555556a41f0 ".github/ISSUE_TEMPLATE") at main/main.c:182
#22 0x0000555555574ec8 in createTagsForEntry (entryName=entryName@entry=0x5555556a41f0 ".github/ISSUE_TEMPLATE") at main/main.c:213
#23 0x0000555555575ca6 in recurseUsingOpendir (dirName=0x5555556941db ".github") at main/main.c:112
#24 recurseIntoDirectory (dirName=dirName@entry=0x5555556941db ".github") at main/main.c:182
#25 0x0000555555574ec8 in createTagsForEntry (entryName=0x5555556941db ".github") at main/main.c:213
#26 0x0000555555575c58 in recurseUsingOpendir (dirName=0x555555655880 ".") at main/main.c:112
#27 recurseIntoDirectory (dirName=dirName@entry=0x555555655880 ".") at main/main.c:182
#28 0x0000555555574ec8 in createTagsForEntry (entryName=0x555555655880 ".") at main/main.c:--Type <RET> for more, q to quit, c to continue without paging--
213
#29 0x000055555557cf51 in createTagsForArgs (args=0x555555655820) at main/main.c:262
#30 batchMakeTags (args=0x555555655820, user=<optimized out>) at main/main.c:356
#31 0x0000555555572382 in runMainLoop (args=0x555555655820) at main/main.c:328
#32 ctags_cli_main (argc=<optimized out>, argv=0x7fffffffe140) at main/main.c:575
#33 main (argc=<optimized out>, argv=0x7fffffffe138) at main/cmd.c:21
(gdb)
```

The version of ctags:

```
openssl@stitny (master)$ ctags --version
Universal Ctags 0.0.0(0+git~c77db554), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 26 2019, 00:00:00
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc
openssl@stitny (master)$
```

From the openSUSE/Factory package.

**Comment by masatake** [comment]
It is not reproduced.

> Universal Ctags 0.0.0(0+git~c77db554), Copyright (C) 2015 Universal Ctags Team

I searched c77db554 in git log.

```
commit c77db554a391958dc330c03e0975636eab2b1300
Merge: 6ad4e957b ea6c9c938
Author: Karol Samborski <edv.karol@gmail.com>
Date:   Sun Aug 25 20:48:39 2019 +0200
```

It looks you are using too old version.
Could you try the latest code?
