### ISSUE TITLE
misc/man-test.py third argument can't be an absolute path

### ISSUE THREAD

**Issue by leleliu008** [universal-ctags/ctags#2962]
```
/usr/local/bin/python3 /Users/leleliu008/git/ctags/misc/man-test.py /Users/leleliu008/git/ctags/build.d/test/man /Users/leleliu008/git/ctags/build.d/ctags /Users/leleliu008/git/ctags/man/ctags-lang-*.7.rst.in
```
```
Traceback (most recent call last):
  File "/Users/leleliu008/git/ctags/misc/man-test.py", line 256, in <module>
    sys.exit(0 if man_tests (tmpdir, ctags, sys.argv[3:]) else 1)
  File "/Users/leleliu008/git/ctags/misc/man-test.py", line 246, in man_tests
    if not man_test(tmpdir, ctags, m):
  File "/Users/leleliu008/git/ctags/misc/man-test.py", line 231, in man_test
    r = run_test_case (tmpdir, ctags, t)
  File "/Users/leleliu008/git/ctags/misc/man-test.py", line 90, in run_test_case
    subprocess.run(cmdline, cwd=d, stdout=h)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/leleliu008/git/ctags//Users/leleliu008/git/ctags/build.d/ctags'
```
relative code:
```C
ctags = os.getcwd() + '/' + sys.argv[2]
```
[here](https://github.com/universal-ctags/ctags/blob/master/misc/man-test.py#L255)

**Comment by leleliu008** [comment]
I changed to `ctags = os.path.abspath(sys.argv[2])`, it works for me.

**Comment by masatake** [comment]
Could you make a pull request for the change that works fine for you and merge it?
