### ISSUE TITLE
segmentation fault when parsing Rakefile

### ISSUE THREAD

**Issue by Safari77** [universal-ctags/ctags#3333]
The name of the parser:
Ruby

The command line you used to run ctags:

```
$ ctags --options=NONE -R
```

The content of input file:

```
  if c?(:PO4A_WORKS)
    $available_languages[:manpages].each do |language|
      $manpages.each do |manpage|
        name = manpage.gsub(/man\//, "man/#{language}/")
        file name            => [ name.ext('xml'),     "doc/man/po4a/po/#{language}.po" ]
        file name.ext('xml') => [ manpage.ext('.xml'), "doc/man/po4a/po/#{language}.po" ] do |t|
          runq "po4a", "#{manpage.ext('.xml')} (#{language})", "#{c(:PO4A_TRANSLATE)} #{c(:PO4A_TRANSLATE_FLAGS)} -m #{manpage.ext('.xml')} -p doc/man/po4a/po/#{language}.po -l #{t.name}", :filter_output => $po4a_output_filter
        end
      end
    end
  end
```

The version of ctags:

```
Universal Ctags 5.9.0, Copyright (C) 2015-2022 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jul 27 2021, 00:00:00
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc, +optscript, +pcre2
```

How do you get ctags binary:
Built using Fedora 35 .spec 

Output:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000006833a9 in readTask (cp=0x7fffffffb340, variable=0x7fffffffaf80) at parsers/rake.c:113
113				const char *end = strstr((const char *)start, vStringValue (vstr));
=> 0x00000000006833a9 <readTask+649>:	48 8b 30	mov    (%rax),%rsi
(gdb) bt
#0  0x00000000006833a9 in readTask (cp=0x7fffffffb340, variable=0x7fffffffaf80) at parsers/rake.c:113
#1  0x0000000000682b60 in parseTask (s=0xaa3ee0 <rakeSubparser>, kind=2, cp=0x7fffffffb340) at parsers/rake.c:158
#2  0x0000000000682685 in lineNotify (s=0xaa3ee0 <rakeSubparser>, cp=0x7fffffffb340) at parsers/rake.c:204
#3  0x0000000000692b6c in notifyLine (cp=0x7fffffffb340) at parsers/ruby.c:946
#4  0x000000000068e8f0 in findRubyTags () at parsers/ruby.c:1142
#5  0x0000000000539367 in createTagsForFile (language=104, passCount=1) at main/parse.c:3757
#6  0x000000000052b0ac in createTagsWithFallback1 (language=104, exclusive_subparser=0x0) at main/parse.c:3907
#7  0x000000000052aa42 in runParserInNarrowedInputStream (language=104, startLine=0, startCharOffset=0, endLine=0, endCharOffset=0, sourceLineOffset=0, 
    promise=0) at main/parse.c:3976
#8  0x000000000053a107 in forcePromises () at main/promise.c:177
#9  0x00000000005396c2 in createTagsWithFallback (fileName=0x62d00000048b "Rakefile", language=96, mio=0x0, mtime=0, failureInOpenning=0x7fffffffb9e0)
    at main/parse.c:4000
#10 0x000000000052c167 in parseMio (fileName=0x62d00000048b "Rakefile", language=96, mio=0x0, mtime=0, useSourceFileTagPath=true, clientData=0x0)
    at main/parse.c:4160
#11 0x000000000052bd03 in parseFileWithMio (fileName=0x62d00000048b "Rakefile", mio=0x0, clientData=0x0) at main/parse.c:4207
#12 0x000000000052b821 in parseFile (fileName=0x62d00000048b "Rakefile") at main/parse.c:4143
#13 0x000000000050f581 in createTagsForEntry (entryName=0x62d00000048b "Rakefile") at main/main.c:221
#14 0x00000000005107a5 in recurseUsingOpendir (dirName=0x963aa0 <str> ".") at main/main.c:115
#15 0x000000000051068a in recurseIntoDirectory (dirName=0x963aa0 <str> ".") at main/main.c:184
#16 0x000000000050fdce in batchMakeTags (args=0x604000000010, user=0x0) at main/main.c:373
#17 0x00000000005104a0 in runMainLoop (args=0x604000000010) at main/main.c:332
#18 0x000000000050f6af in ctags_cli_main (argc=2, argv=0x7fffffffc0a0) at main/main.c:586
#19 0x000000000050ea52 in main (argc=2, argv=0x7fffffffc098) at main/cmd.c:21
```
(I made a short test case from mkvtoolnix Rakefile)

**Comment by masatake** [comment]
Thank you for reporting. However, the issue is not reproduced.

```
[jet@living]~/var/ctags-github% rpm -qf /usr/bin/ctags      
ctags-5.9-1.20210725.0.fc35.x86_64
[jet@living]~/var/ctags-github% cat /tmp/Rakefile     
if c?(:PO4A_WORKS)
  $available_languages[:manpages].each do |language|
    $manpages.each do |manpage|
      name = manpage.gsub(/man\//, "man/#{language}/")
      file name            => [ name.ext('xml'),     "doc/man/po4a/po/#{language}.po" ]
      file name.ext('xml') => [ manpage.ext('.xml'), "doc/man/po4a/po/#{language}.po" ] do |t|
        runq "po4a", "#{manpage.ext('.xml')} (#{language})", "#{c(:PO4A_TRANSLATE)} #{c(:PO4A_TRANSLATE_FLAGS)} -m #{manpage.ext('.xml')} -p doc/man/po4a/po/#{language}.po -l #{t.name}", :filter_output => $po4a_output_filter
      end
    end
  end
end

[jet@living]~/var/ctags-github%  /usr/bin/ctags --options=NONE /tmp/Rakefile 
ctags: Notice: No options will be read from files or environment
[jet@living]~/var/ctags-github% valgrind  /usr/bin/ctags --options=NONE /tmp/Rakefile
==3276142== Memcheck, a memory error detector
==3276142== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3276142== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==3276142== Command: /usr/bin/ctags --options=NONE /tmp/Rakefile
==3276142== 
ctags: Notice: No options will be read from files or environment
==3276142== 
==3276142== HEAP SUMMARY:
==3276142==     in use at exit: 18,101 bytes in 652 blocks
==3276142==   total heap usage: 8,518 allocs, 7,866 frees, 357,351 bytes allocated
==3276142== 
==3276142== LEAK SUMMARY:
==3276142==    definitely lost: 0 bytes in 0 blocks
==3276142==    indirectly lost: 0 bytes in 0 blocks
==3276142==      possibly lost: 0 bytes in 0 blocks
==3276142==    still reachable: 18,101 bytes in 652 blocks
==3276142==         suppressed: 0 bytes in 0 blocks
==3276142== Rerun with --leak-check=full to see details of leaked memory
==3276142== 
==3276142== For lists of detected and suppressed errors, rerun with: -s
==3276142== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by masatake** [comment]
Thank you. Reproduced.

```
[jet@living]~/var/ctags-github% cat /tmp/Rakefile                   
if c?(:PO4A_WORKS)
  $available_languages[:manpages].each do |language|
    $manpages.each do |manpage|
      name = manpage.gsub(/man\//, "man/#{language}/")
      file name            => [ name.ext('xml'),     "doc/man/po4a/po/#{language}.po" ]
      file name.ext('xml') => [ manpage.ext('.xml'), "doc/man/po4a/po/#{language}.po" ] do |t|
        runq "po4a", "#{manpage.ext('.xml')} (#{language})", "#{c(:PO4A_TRANSLATE)} #{c(:PO4A_TRANSLATE_FLAGS)} -m #{manpage.ext('.xml')} -p doc/man/po4a/po/#{language}.po -l #{t.name}", :filter_output => $po4a_output_filter
      end
    end
  end
end
$ ./ctags --options=NONE /tmp/Rakefile
ctags: Notice: No options will be read from files or environment
zsh: segmentation fault (core dumped)  ./ctags --options=NONE /tmp/Rakefile
```

**Comment by masatake** [comment]
I found I took a stupid mistake:
```
diff --git a/parsers/rake.c b/parsers/rake.c
index 75f156342..18ba43d23 100644
--- a/parsers/rake.c
+++ b/parsers/rake.c
@@ -109,6 +109,7 @@ static vString *readTask (const unsigned char **cp, bool *variable)
                        vStringDelete (vstr);
                        vstr = NULL;
                }
+               else
                {
                        const char *end = strstr((const char *)start, vStringValue (vstr));
                        if (end)
```

**Comment by masatake** [comment]
> (I made a short test case from mkvtoolnix Rakefile)

Thank you very much for taking your time for making the input short.

**Comment by Safari77** [comment]
> > (I made a short test case from mkvtoolnix Rakefile)
> 
> Thank you very much for taking your time for making the input short.

I did a binary search so it didn't need much time 🤓
