### ISSUE TITLE
Question about tag scopes not being output

### ISSUE THREAD

**Issue by bangroot** [universal-ctags/ctags#710]
Not sure if you want questions here, but someone recommended that I ask here vs. my [stackoverflow question](http://stackoverflow.com/questions/34098349/adding-tag-scopes-in-universal-ctags).

I'm currently writing an external tags generator for universal-ctags to get better groovy support. Given that groovy already has AST support, I'm just implementing via a simple groovy script (see [here](https://github.com/bangroot/ctags-castle/blob/master/home/.ctags.d/drivers/groovytags) if you care).

My problem is that even though I output class:<ClassName> in the extra fields, universal-ctags drops it from the output ... I presume there is something telling it what languages support which tag scopes.

For instance, when I run with the same flags that TagBar uses ...

```bash
ctags -f - --format=2 --excmd=pattern --extra= --fields=nksaSmt
```

... for Java source I'll get output akin to:

```
ThisClass       src/main/java/ThisClass.java  /^      public ThisClass(String name) {}$/;"    m       line:24 class:ThisClass access:public   signature:(String name)
```

However, when run against a file using my xcmd through ctags, the output is:

```
start   src/main/groovy/Main.groovy    /^      def start(String m) {$/;"      m       line:34 access:public   signature:(String m)
```

Even though the output directly from my xcmd shows the proper output:

```
start   src/main/groovy/Main.groovy       /^      def start(String m) {$/;"      m       class:Main      access:public      signature:(String m)   line:34
```

Is there some way to get universal-ctags to echo out my tag scopes?

**Comment by masatake** [comment]
Thank you for contacting. This is the place for you:
```
The goal of the project is preparing and maintaining common/unified working
space where people interested in making ctags better can work
together.
```

I would like to try your groovytags for debugging. The problem is that I don't know well about groovy.
The language processor of groovy may be installed with the package system of Fedora, I'm using, without trouble. How about libraries? I guess groovy also has its own package system like cpan of perl.
Could you should me short hints for trying your xcmd?

As far as trying coffeetags, ctags can get scope information from a xcmd.

**Comment by masatake** [comment]
groovytags works; groovy is just needed.
I found some empty lines in its output:
```
$  /tmp/groovytags  ./groovytags  | head
!_TAG_FILE_FORMAT       2       /extended format/
!_TAG_FILE_SORTED       0       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Dave Brown  /bangroot@gmail.com/
!_TAG_PROGRAM_NAME      groovytags      //
!_TAG_PROGRAM_URL       https://github.com/bangroot/ctags-castle     /GitHub repository/
!_TAG_PROGRAM_VERSION   0.1.0   //
script1449576308330	./groovytags	/^if (!args) {$/;"	c	access:public	line:17

AstNodeToScriptVisitor	./groovytags	/^class AstNodeToScriptVisitor extends PrimaryClassNodeOperation implements GroovyClassVisitor {$/;"	c	access:public	line:66
WHITESPACE	./groovytags	/^	private static final String WHITESPACE = "[ \\t]*"$/;"	f	class:AstNodeToScriptVisitor	access:private	line:67
```

in addition I got an exception.

```
Unable to produce AST for this phase due to earlier compilation error:
startup failed:
General error during conversion: -2

java.lang.ArrayIndexOutOfBoundsException: -2
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at java_util_List$get.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at AstNodeToScriptVisitor.visitMethod(groovytags:195)
	at org.codehaus.groovy.ast.GroovyClassVisitor$visitMethod$0.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at AstNodeToScriptVisitor.visitConstructor(groovytags:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at AstNodeToScriptVisitor$_visitClass_closure3.doCall(groovytags:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:87)
	at AstNodeToScriptVisitor.visitClass(groovytags:180)
	at org.codehaus.groovy.ast.GroovyClassVisitor$visitClass.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at AstNodeToScriptVisitor.call(groovytags:88)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1055)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:591)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:569)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:546)
	at org.codehaus.groovy.control.CompilationUnit$compile$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at groovytags.run(groovytags:42)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
	at groovy.lang.GroovyShell.run(GroovyShell.java:524)
	at groovy.lang.GroovyShell.run(GroovyShell.java:513)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:652)
	at groovy.ui.GroovyMain.run(GroovyMain.java:384)
	at groovy.ui.GroovyMain.process(GroovyMain.java:370)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:129)
	at groovy.ui.GroovyMain.main(GroovyMain.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)

1 error
Fix the above error(s) and then press Refresh
```

Anyway I can debug ctags side with this.

**Comment by masatake** [comment]
See https://github.com/bangroot/ctags-castle/pull/1 . 
Now you code works fine:
```
[yamato@x201]~/var/ctags-github% cat libexec/drivers/groovytags
cat libexec/drivers/groovytags
#!/bin/sh
{
    COMMAND_NOT_FOUND=127

    if ! type groovytags; then
	exit ${COMMAND_NOT_FOUND}
    fi
} > /dev/null 2>&1

case "$1" in
    --list-kinds*)
	groovytags --list-kinds
	exit $?
	;;
    -*)
	echo "unknown option: $1" 1>&2
	exit 1
	;;
    *)
	groovytags "$1"
	exit $?
	;;
esac

[yamato@x201]~/var/ctags-github% ./ctags -o - --libexec-dir=./libexec --langdef=groovy --xcmd-groovy=groovytags --language-force=groovy ~/bin/groovytags  | head
<groovytags --language-force=groovy ~/bin/groovytags  | head
AstNodeToScriptVisitor	/home/yamato/bin/groovytags	/^	def AstNodeToScriptVisitor(String fileName, Writer writer, boolean showScriptClass = true) {$/;"	m	class:AstNodeToScriptVisitor
AstNodeToScriptVisitor	/home/yamato/bin/groovytags	/^class AstNodeToScriptVisitor extends PrimaryClassNodeOperation implements GroovyClassVisitor {$/;"	c
WHITESPACE	/home/yamato/bin/groovytags	/^	private static final String WHITESPACE = "[ \\t]*"$/;"	f	class:AstNodeToScriptVisitor
_indent	/home/yamato/bin/groovytags	/^	String _indent = ''$/;"	f	class:AstNodeToScriptVisitor
_out	/home/yamato/bin/groovytags	/^	private final Writer _out$/;"	f	class:AstNodeToScriptVisitor
call	/home/yamato/bin/groovytags	/^	void call(SourceUnit source, GeneratorContext context, ClassNode classNode) {$/;"	m	class:AstNodeToScriptVisitor
classNameStack	/home/yamato/bin/groovytags	/^	Stack<String> classNameStack = new Stack<String>()$/;"	f	class:AstNodeToScriptVisitor
fileName	/home/yamato/bin/groovytags	/^	String fileName$/;"	f	class:AstNodeToScriptVisitor
getAccessString	/home/yamato/bin/groovytags	/^	String getAccessString(int mods) {$/;"	m	class:AstNodeToScriptVisitor
getRealLineNumber	/home/yamato/bin/groovytags	/^	int getRealLineNumber(def node) {$/;"	m	class:AstNodeToScriptVisitor
```

**Comment by masatake** [comment]
Now I understand well why you want to pass multipe files to xcmd from ctags at once.
However, I cannot find much time for the function now. I'm working hard for 1.0.0 now.

**Comment by bangroot** [comment]
Wow, awesome. thanks for your help!

**Comment by mMontu** [comment]
I'd like to generate groovy tags using the work on this issue.
I've copied the [groovytags file from ctags-castle](https://github.com/bangroot/ctags-castle/blob/master/home/.ctags.d/drivers/groovytags) into `~/.ctags.d/drivers/`, but it didn't work (`ignoring vars/xpod3.groovy (unknown language/language disabled)`).

I did a quick search on the universal-ctags documentation but couldn't find what I'm missing.
Updating universal-ctags to the latest master didn't help.

@bangroot, @masatake, do you have any ideas?

**Comment by masatake** [comment]
xcmd, a feature invoking an external tags generator, was removed.
https://github.com/universal-ctags/ctags/issues/1442

**Comment by mMontu** [comment]
Oh, that's why I couldn't find any reference to the option you used in your previous comment.

I've tried to switch to a regular definition on the `~/.ctags` as [this](https://github.com/majutsushi/tagbar/wiki#groovy), but for some reason it isn't being loaded.
But maybe this should be in a separate issue.

**Comment by mMontu** [comment]
I've tried `~/.ctags.d/.ctags`, but from #1582 it seems it should be `.ctags.d/foo.ctags`.
